#!/usr/bin/env bash

# =============================
# Monodrive Dotfiles Installer
# =============================

REPO_URL="https://github.com/magic3eraltd/dotfiles.git"
BARE_DIR="$HOME/.dotfiles"
BACKUP_DIR="$HOME/.config-backup"
I3_DIR="$HOME/.config/i3"

echo "Installing Monodrive dotfiles..."

# -----------------------------
# 1. Clone repo (bare)
# -----------------------------
if [ ! -d "$BARE_DIR" ]; then
    git clone --bare "$REPO_URL" "$BARE_DIR"
else
    echo "Bare repository already exists at $BARE_DIR"
fi

CONFIG="git --git-dir=$BARE_DIR --work-tree=$HOME"

mkdir -p "$BACKUP_DIR"

# -----------------------------
# 2. Checkout + backup conflicts
# -----------------------------
$CONFIG checkout 2>&1 | grep -E "^\s+." | awk '{print $1}' | while read -r file; do
    [ -z "$file" ] && continue
    mkdir -p "$(dirname "$BACKUP_DIR/$file")"
    mv "$HOME/$file" "$BACKUP_DIR/$file"
done

$CONFIG checkout
$CONFIG config --local status.showUntrackedFiles no

# -----------------------------
# 3. MONITOR SETUP (IMPORTANT)
# -----------------------------

echo ""
echo "Detected monitors:"
xrandr --query | grep " connected"
echo ""

read -p "How many monitors do you use? (1/2/3): " COUNT

read -p "Primary monitor (e.g. DP-0): " M1

if [ "$COUNT" -ge 2 ]; then
    read -p "Second monitor (e.g. HDMI-0): " M2
else
    M2=""
fi

if [ "$COUNT" -ge 3 ]; then
    read -p "Third monitor (e.g. DP-1): " M3
else
    M3=""
fi

mkdir -p "$I3_DIR"

# -----------------------------
# 4. Generate workspace mapping
# -----------------------------

CONF_FILE="$I3_DIR/generated_outputs.conf"

cat > "$CONF_FILE" <<EOF
# Auto-generated by Monodrive installer
EOF

# Workspaces 1–5 -> primary
for i in {1..5}; do
    echo "workspace $i output $M1" >> "$CONF_FILE"
done

# Workspaces 6–10 -> secondary (if exists, else fallback to primary)
if [ -n "$M2" ]; then
    for i in {6..10}; do
        echo "workspace $i output $M2" >> "$CONF_FILE"
    done
else
    for i in {6..10}; do
        echo "workspace $i output $M1" >> "$CONF_FILE"
    done
fi

# Workspaces 11–15 -> third (if exists, else fallback to primary)
if [ -n "$M3" ]; then
    for i in {11..15}; do
        echo "workspace $i output $M3" >> "$CONF_FILE"
    done
else
    for i in {11..15}; do
        echo "workspace $i output $M1" >> "$CONF_FILE"
    done
fi

# -----------------------------
# 5. Patch monitors.sh (template replacement)
# -----------------------------

MONITORS_SCRIPT="$HOME/.config/i3/scripts/monitors.sh"

sed -i \
    -e "s/@PRIMARY@/$M1/g" \
    -e "s/@SECONDARY@/$M2/g" \
    -e "s/@THIRD@/$M3/g" \
    "$MONITORS_SCRIPT"

# -----------------------------
# 6. FINAL MESSAGE
# -----------------------------

echo ""
echo "Monodrive installed successfully!"
echo "Workspace config: $CONF_FILE"
echo "Monitor script configured: $MONITORS_SCRIPT"
echo "Backups: $BACKUP_DIR"
