#!/usr/bin/env bash

set -e

# =============================
# Monodrive Dotfiles Installer
# =============================

REPO_URL="https://github.com/magic3eraltd/dotfiles.git"
BARE_DIR="$HOME/.dotfiles"
BACKUP_DIR="$HOME/.config-backup"
I3_DIR="$HOME/.config/i3"

echo "Installing Monodrive dotfiles..."

# -----------------------------
# 0. SYSTEM DEPENDENCIES (PACMAN)
# -----------------------------

echo ""
echo "Installing system dependencies..."

sudo pacman -S --needed \
i3-wm \
xorg-xrandr \
xorg-xsetroot \
git \
feh \
polybar \
rofi \
dunst \
picom \
neovim \
thunar \
fastfetch \
udiskie \
udisks2 \
ntfs-3g \
cava \
cmatrix

# -----------------------------
# 1. YAY BOOTSTRAP (if missing)
# -----------------------------

echo ""
echo "Checking yay..."

if ! command -v yay >/dev/null 2>&1; then
    echo "yay not found, installing..."

    sudo pacman -S --needed git base-devel

    git clone https://aur.archlinux.org/yay.git /tmp/yay
    (cd /tmp/yay && makepkg -si --noconfirm)

    rm -rf /tmp/yay
else
    echo "yay already installed"
fi

# -----------------------------
# 2. AUR PACKAGES
# -----------------------------

echo ""
echo "Installing AUR packages..."

yay -S --needed \
wezterm \
ttf-jetbrains-mono-nerd \
autotiling

# -----------------------------
# 3. CLONE DOTFILES (BARE REPO)
# -----------------------------

if [ ! -d "$BARE_DIR" ]; then
    git clone --bare "$REPO_URL" "$BARE_DIR"
else
    echo "Bare repository already exists at $BARE_DIR"
fi

CONFIG="git --git-dir=$BARE_DIR --work-tree=$HOME"

mkdir -p "$BACKUP_DIR"

# -----------------------------
# 4. CHECKOUT + BACKUP
# -----------------------------

$CONFIG checkout 2>&1 | grep -E "^\s+." | awk '{print $1}' | while read -r file; do
    [ -z "$file" ] && continue
    mkdir -p "$(dirname "$BACKUP_DIR/$file")"
    mv "$HOME/$file" "$BACKUP_DIR/$file"
done

$CONFIG checkout
$CONFIG config --local status.showUntrackedFiles no

# -----------------------------
# 5. MONITOR SETUP
# -----------------------------

echo ""
echo "Detected monitors:"
xrandr --query | grep " connected"
echo ""

read -p "How many monitors do you use? (1/2/3): " COUNT

read -p "Primary monitor: " M1

M2=""
M3=""

if [ "$COUNT" -ge 2 ]; then
    read -p "Second monitor: " M2
fi

if [ "$COUNT" -ge 3 ]; then
    read -p "Third monitor: " M3
fi

mkdir -p "$I3_DIR"

CONF_FILE="$I3_DIR/generated_outputs.conf"

# -----------------------------
# 6. GENERATE WORKSPACES
# -----------------------------

{
echo "# Auto-generated by Monodrive installer"

# 1–5 primary
for i in {1..5}; do
    echo "workspace $i output $M1"
done

# 6–10 secondary (fallback to primary)
for i in {6..10}; do
    if [ -n "$M2" ]; then
        echo "workspace $i output $M2"
    else
        echo "workspace $i output $M1"
    fi
done

# 11–15 third (fallback to primary)
for i in {11..15}; do
    if [ -n "$M3" ]; then
        echo "workspace $i output $M3"
    else
        echo "workspace $i output $M1"
    fi
done

} > "$CONF_FILE"

# -----------------------------
# 7. PATCH MONITORS SCRIPT
# -----------------------------

MONITORS_SCRIPT="$HOME/.config/i3/scripts/monitors.sh"

if [ -f "$MONITORS_SCRIPT" ]; then
    sed -i \
        -e "s/@PRIMARY@/$M1/g" \
        -e "s/@SECONDARY@/$M2/g" \
        -e "s/@THIRD@/$M3/g" \
        "$MONITORS_SCRIPT"
fi

# -----------------------------
# 8. FINAL MESSAGE
# -----------------------------

echo ""
echo "Monodrive installed successfully!"
echo "Workspace config: $CONF_FILE"
echo "Backup: $BACKUP_DIR"
echo "Done."
